CREATE TABLE [dbo].[Note]
(
	[NoteId] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [UserId] BIGINT NOT NULL, 
    [Name] NVARCHAR(30) NOT NULL, 
    [Text] NVARCHAR(300) NOT NULL,
    [Deleted] BIT NOT NULL DEFAULT 0,
    [DateCreated] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
    CONSTRAINT [FK_Note_User] FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
)
