CREATE TABLE [dbo].[User]
(
	[UserId] INT NOT NULL PRIMARY KEY IDENTITY, 
    [DiscordUserId] DECIMAL(20) NOT NULL, 
    [UserName] NVARCHAR(100) NOT NULL, 
    [DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT [CK_User_DiscordUserId] CHECK (DiscordUserId >= 0 AND DiscordUserId <= 18446744073709551615)
)
